version: "3.8"

services:
  muazzin-bot:
    build: .
    container_name: muazzin_bot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_URL=${API_URL}
    command: ["python", "run.py"]

  notification-sender:
    build: .
    container_name: notification_sender
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_URL=${API_URL}
    command: ["python", "notification-sender.py"]
